# Generated by Django 4.2.13 on 2025-10-19 21:55

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_instancesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationcomponent",
            options={
                "ordering": ["name"],
                "verbose_name": "annotation component",
                "verbose_name_plural": "annotation components",
            },
        ),
        migrations.AlterModelOptions(
            name="annotationtaxonomy",
            options={
                "ordering": ("order",),
                "verbose_name": "annotation taxonomy",
                "verbose_name_plural": "annotation taxonomies",
            },
        ),
        migrations.AlterModelOptions(
            name="annotationtype",
            options={
                "verbose_name": "annotation type",
                "verbose_name_plural": "annotation types",
            },
        ),
        migrations.AlterModelOptions(
            name="block",
            options={
                "ordering": ("order",),
                "verbose_name": "block",
                "verbose_name_plural": "blocks",
            },
        ),
        migrations.AlterModelOptions(
            name="blocktype",
            options={
                "verbose_name": "block type",
                "verbose_name_plural": "block types",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.AlterModelOptions(
            name="documentpart",
            options={
                "ordering": ("order",),
                "verbose_name": "document part",
                "verbose_name_plural": "document parts",
            },
        ),
        migrations.AlterModelOptions(
            name="documentparttype",
            options={
                "verbose_name": "document part type",
                "verbose_name_plural": "document part types",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttag",
            options={
                "verbose_name": "document tag",
                "verbose_name_plural": "document tags",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "document type",
                "verbose_name_plural": "document types",
            },
        ),
        migrations.AlterModelOptions(
            name="imageannotation",
            options={
                "verbose_name": "image annotation",
                "verbose_name_plural": "image annotations",
            },
        ),
        migrations.AlterModelOptions(
            name="line",
            options={
                "ordering": ("order",),
                "verbose_name": "line",
                "verbose_name_plural": "lines",
            },
        ),
        migrations.AlterModelOptions(
            name="linetranscription",
            options={
                "verbose_name": "line transcription",
                "verbose_name_plural": "line transcriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="linetype",
            options={"verbose_name": "line type", "verbose_name_plural": "line types"},
        ),
        migrations.AlterModelOptions(
            name="metadata",
            options={
                "ordering": ["name"],
                "verbose_name": "metadata",
                "verbose_name_plural": "metadata",
            },
        ),
        migrations.AlterModelOptions(
            name="ocrmodel",
            options={
                "ordering": ["-version_updated_at"],
                "permissions": (("can_train", "Can train models"),),
                "verbose_name": "OCR model",
                "verbose_name_plural": "OCR models",
            },
        ),
        migrations.AlterModelOptions(
            name="ocrmodeldocument",
            options={
                "verbose_name": "OCR model document",
                "verbose_name_plural": "OCR model documents",
            },
        ),
        migrations.AlterModelOptions(
            name="ocrmodelright",
            options={
                "verbose_name": "OCR model right",
                "verbose_name_plural": "OCR model rights",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelOptions(
            name="script",
            options={
                "ordering": ["name"],
                "verbose_name": "script",
                "verbose_name_plural": "scripts",
            },
        ),
        migrations.AlterModelOptions(
            name="textualwitness",
            options={
                "verbose_name": "textual witness",
                "verbose_name_plural": "textual witnesses",
            },
        ),
        migrations.AlterModelOptions(
            name="transcription",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "transcription",
                "verbose_name_plural": "transcriptions",
            },
        ),
        migrations.AddField(
            model_name="script",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="ocrmodel",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=core.models.models_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mlmodel", "traineddata"]
                    )
                ],
            ),
        ),
    ]
