# Generated by Django 4.2.13 on 2025-10-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_add_hebrew_script_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtype",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="documentparttype",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="linetype",
            name="name_he",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
