# Generated by Django 4.2.23 on 2025-10-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0078_populate_typology_hebrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('spelling', 'שגיאת איות / Spelling error'), ('pattern', 'תבנית שגיאה / Error pattern'), ('confidence', 'ביטחון נמוך / Low confidence'), ('manual', 'סומן ידנית / Manually marked')], max_length=20, verbose_name='סוג שגיאה')),
                ('severity', models.CharField(choices=[('critical', 'קריטי / Critical'), ('high', 'גבוה / High'), ('medium', 'בינוני / Medium'), ('low', 'נמוך / Low')], max_length=20, verbose_name='חומרה')),
                ('status', models.CharField(choices=[('pending', 'ממתין / Pending'), ('corrected', 'תוקן / Corrected'), ('ignored', 'התעלם / Ignored'), ('false_positive', 'לא שגיאה / False positive')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('word', models.CharField(blank=True, max_length=200, verbose_name='מילה שגויה')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='מיקום התחלה')),
                ('end_position', models.IntegerField(blank=True, null=True, verbose_name='מיקום סיום')),
                ('suggestions', models.JSONField(default=list, help_text='List of suggested corrections', verbose_name='הצעות תיקון')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('confidence_score', models.FloatField(blank=True, help_text='OCR confidence score (0.0-1.0)', null=True, verbose_name='ציון ביטחון')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='זוהה ב')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='טופל ב')),
                ('line_transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_errors', to='core.linetranscription', verbose_name='תמלול שורה')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='טופל על ידי')),
            ],
            options={
                'verbose_name': 'שגיאה מזוהה',
                'verbose_name_plural': 'שגיאות מזוהות',
                'ordering': ['-severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_from', models.CharField(max_length=200, verbose_name='תבנית שגויה')),
                ('pattern_to', models.CharField(max_length=200, verbose_name='תבנית מתוקנת')),
                ('language', models.CharField(max_length=10, verbose_name='שפה')),
                ('pattern_type', models.CharField(choices=[('character', 'תו בודד / Single character'), ('sequence', 'רצף תווים / Character sequence'), ('word', 'מילה / Word'), ('regex', 'ביטוי רגולרי / Regex pattern')], default='character', max_length=50, verbose_name='סוג תבנית')),
                ('frequency', models.IntegerField(default=1, help_text='How many times this pattern was observed', verbose_name='תדירות')),
                ('confidence', models.FloatField(default=0.5, help_text='Confidence score (0.0-1.0)', verbose_name='ביטחון')),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate when suggested (0.0-1.0)', verbose_name='אחוז הצלחה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., common surrounding characters)', verbose_name='הקשר')),
            ],
            options={
                'verbose_name': 'תבנית שגיאה',
                'verbose_name_plural': 'תבניות שגיאה',
                'ordering': ['-frequency', '-confidence'],
                'unique_together': {('pattern_from', 'pattern_to', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ErrorCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=500, verbose_name='טקסט מקורי')),
                ('corrected_text', models.CharField(max_length=500, verbose_name='טקסט מתוקן')),
                ('was_from_suggestion', models.BooleanField(default=False, help_text='Was this correction from a suggested option?', verbose_name='מהצעה?')),
                ('suggestion_rank', models.IntegerField(blank=True, help_text='Which suggestion was chosen (1-5)', null=True, verbose_name='דירוג הצעה')),
                ('corrected_at', models.DateTimeField(auto_now_add=True, verbose_name='תוקן ב')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='תוקן על ידי')),
                ('detected_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='core.detectederror', verbose_name='שגיאה')),
            ],
            options={
                'verbose_name': 'תיקון',
                'verbose_name_plural': 'תיקונים',
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomDictionaryWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='מילה')),
                ('language', models.CharField(default='he', help_text='Language code (he, ar, en)', max_length=10, verbose_name='שפה')),
                ('category', models.CharField(blank=True, help_text='e.g., "שמות", "מקומות", "מונחים"', max_length=50, verbose_name='קטגוריה')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='נוסף ב')),
                ('usage_count', models.IntegerField(default=0, verbose_name='ספירת שימוש')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נוסף על ידי')),
            ],
            options={
                'verbose_name': 'מילה במילון מותאם',
                'verbose_name_plural': 'מילון מותאם אישית',
                'ordering': ['-usage_count', 'word'],
            },
        ),
        migrations.AddIndex(
            model_name='detectederror',
            index=models.Index(fields=['line_transcription', 'status'], name='core_detect_line_tr_7f6401_idx'),
        ),
        migrations.AddIndex(
            model_name='detectederror',
            index=models.Index(fields=['error_type', 'severity'], name='core_detect_error_t_a65131_idx'),
        ),
        migrations.AddIndex(
            model_name='detectederror',
            index=models.Index(fields=['status', 'detected_at'], name='core_detect_status_a78093_idx'),
        ),
    ]
