# Generated by Django 4.2.23 on 2025-10-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_text_alignment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='training_completed_at',
            field=models.DateTimeField(blank=True, help_text='When training completed', null=True),
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='training_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Total training duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='training_epoch_history',
            field=models.JSONField(blank=True, help_text='Per-epoch accuracy and loss history', null=True),
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='training_started_at',
            field=models.DateTimeField(blank=True, help_text='When training started', null=True),
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='training_total_epochs',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total epochs completed'),
        ),
    ]
