# Generated by Django 4.2.13 on 2025-10-26 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0080_text_alignment_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "passim_n",
                    models.IntegerField(default=7, help_text="Character n-gram order"),
                ),
                (
                    "passim_cores",
                    models.IntegerField(default=6, help_text="Number of CPU cores"),
                ),
                (
                    "passim_memory",
                    models.IntegerField(default=8, help_text="Memory in GB"),
                ),
                (
                    "passim_driver_memory",
                    models.IntegerField(default=4, help_text="Driver memory in GB"),
                ),
                (
                    "levenshtein_threshold",
                    models.FloatField(
                        default=0.8, help_text="Minimum Levenshtein ratio (0.0-1.0)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing Data"),
                            ("running_passim", "Running Passim"),
                            ("processing", "Processing Results"),
                            ("importing", "Importing to eScriptorium"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("total_aligned_lines", models.IntegerField(default=0)),
                (
                    "aligned_gt_texts",
                    models.JSONField(
                        blank=True, default=list, help_text="List of GT texts found"
                    ),
                ),
                ("results_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignment_jobs",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alignment Job",
                "verbose_name_plural": "Alignment Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroundTruthCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Corpus name (e.g., 'Sefaria Tanakh')", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sefaria", "Sefaria API"),
                            ("pdf", "PDF Files"),
                            ("txt", "Text Files"),
                            ("manual", "Manual Entry"),
                            ("other", "Other"),
                        ],
                        default="txt",
                        max_length=50,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True, help_text="Path to source files", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_texts", models.IntegerField(default=0)),
                ("total_characters", models.BigIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gt_corpora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Truth Corpus",
                "verbose_name_plural": "Ground Truth Corpora",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroundTruthText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "content",
                    models.TextField(help_text="Clean text content for alignment"),
                ),
                (
                    "language",
                    models.CharField(
                        default="heb", help_text="Language code", max_length=10
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("character_count", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="taba_pipeline.groundtruthcorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ground Truth Text",
                "verbose_name_plural": "Ground Truth Texts",
                "ordering": ["corpus", "title"],
                "unique_together": {("corpus", "filename")},
            },
        ),
        migrations.CreateModel(
            name="AlignmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_pk",
                    models.IntegerField(help_text="eScriptorium part (page) pk"),
                ),
                ("part_title", models.CharField(max_length=255)),
                ("total_aligned_lines", models.IntegerField(default=0)),
                (
                    "aligned_clusters",
                    models.JSONField(
                        default=list,
                        help_text="Sizes of consecutive aligned line clusters",
                    ),
                ),
                ("max_cluster_size", models.IntegerField(default=0)),
                ("average_levenshtein_ratio", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gt_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignments",
                        to="taba_pipeline.groundtruthtext",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="taba_pipeline.alignmentjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alignment Result",
                "verbose_name_plural": "Alignment Results",
                "ordering": ["job", "-total_aligned_lines"],
            },
        ),
        migrations.AddField(
            model_name="alignmentjob",
            name="gt_corpus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignment_jobs",
                to="taba_pipeline.groundtruthcorpus",
            ),
        ),
        migrations.AddField(
            model_name="alignmentjob",
            name="ocr_transcription",
            field=models.ForeignKey(
                help_text="OCR transcription to align",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignment_jobs_as_ocr",
                to="core.transcription",
            ),
        ),
        migrations.AddField(
            model_name="alignmentjob",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignment_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
