# Generated by Django 4.2.23 on 2025-10-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0081_add_training_analytics_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CERAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ignore_punctuation', models.BooleanField(default=False)),
                ('ignore_case', models.BooleanField(default=False)),
                ('ignore_whitespace', models.BooleanField(default=False)),
                ('ignore_numbers', models.BooleanField(default=False)),
                ('ignore_newlines', models.BooleanField(default=False)),
                ('ignore_chars', models.CharField(blank=True, max_length=255, null=True)),
                ('cer_value', models.FloatField(help_text='Character Error Rate percentage')),
                ('num_correct', models.IntegerField(help_text='Number of correctly recognized characters')),
                ('num_substitutions', models.IntegerField(help_text='Number of substituted characters')),
                ('num_insertions', models.IntegerField(help_text='Number of inserted characters')),
                ('num_deletions', models.IntegerField(help_text='Number of deleted characters')),
                ('total_characters', models.IntegerField(help_text='Total number of characters in ground truth')),
                ('original_lines_count', models.IntegerField(default=0)),
                ('discarded_lines_count', models.IntegerField(default=0)),
                ('processed_lines_count', models.IntegerField(default=0)),
                ('character_statistics', models.JSONField(blank=True, default=list, help_text='Per-character accuracy statistics')),
                ('block_statistics', models.JSONField(blank=True, default=list, help_text='Unicode block statistics', null=True)),
                ('confusion_statistics', models.JSONField(blank=True, default=list, help_text='Character confusion matrix')),
                ('ground_truth_transcription', models.ForeignKey(help_text='Ground truth transcription', on_delete=django.db.models.deletion.CASCADE, related_name='cer_analyses_as_ground_truth', to='core.transcription')),
                ('hypothesis_transcription', models.ForeignKey(help_text='Hypothesis (OCR output) transcription', on_delete=django.db.models.deletion.CASCADE, related_name='cer_analyses_as_hypothesis', to='core.transcription')),
            ],
            options={
                'verbose_name': 'CER Analysis',
                'verbose_name_plural': 'CER Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ground_truth_transcription', 'hypothesis_transcription'], name='cerberus_in_ground__023973_idx'), models.Index(fields=['-created_at'], name='cerberus_in_created_79945d_idx')],
            },
        ),
    ]
