# Generated by Django 4.2.23 on 2025-09-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0080_text_alignment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLanguageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew_support', models.CharField(choices=[('full', 'תמיכה מלאה'), ('partial', 'תמיכה חלקית'), ('none', 'ללא תמיכה'), ('unknown', 'לא נבדק')], default='unknown', help_text='רמת תמיכת עברית במודל', max_length=20)),
                ('hebrew_charset_score', models.FloatField(blank=True, help_text='ניקוד איכות charset עברי (0-1)', null=True)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('analysis_details', models.JSONField(blank=True, default=dict, help_text="פרטי ניתוח מלאים (charset, דוגמאות, וכו')")),
                ('ocr_model', models.OneToOneField(help_text='חיבור למודל OCR מהליבה (בלי לשנות אותה!)', on_delete=django.db.models.deletion.CASCADE, related_name='language_analysis', to='core.ocrmodel')),
            ],
            options={
                'verbose_name': 'ניתוח שפה למודל OCR',
                'verbose_name_plural': 'ניתוחי שפה למודלי OCR',
            },
        ),
    ]
