# Generated by Django 4.2.23 on 2025-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellanguageanalysis',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='ניקוד ודאות כללי (0-1)', null=True),
        ),
    ]
