# Generated by Django 4.2.23 on 2025-10-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0081_add_training_analytics_fields'),
        ('taba_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundtruthcorpus',
            name='language',
            field=models.CharField(default='heb', help_text="Primary language of this corpus (e.g., 'heb', 'ara', 'eng')", max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='document',
            field=models.ForeignKey(help_text='Source document containing OCR to be aligned', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_jobs', to='core.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='gt_corpus',
            field=models.ForeignKey(help_text='Corpus of clean texts to align against', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_jobs', to='taba_pipeline.groundtruthcorpus', verbose_name='Ground Truth Corpus'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='name',
            field=models.CharField(help_text='Descriptive name for this alignment job', max_length=255, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='ocr_transcription',
            field=models.ForeignKey(help_text='OCR transcription to align with ground truth', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_jobs_as_ocr', to='core.transcription', verbose_name='OCR Transcription'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='owner',
            field=models.ForeignKey(help_text='User who created this job', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='passim_cores',
            field=models.IntegerField(default=6, help_text='Number of CPU cores to use for alignment', verbose_name='CPU Cores'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='passim_memory',
            field=models.IntegerField(default=8, help_text='Memory allocation in GB for alignment process', verbose_name='Memory (GB)'),
        ),
        migrations.AlterField(
            model_name='alignmentjob',
            name='passim_n',
            field=models.IntegerField(default=7, help_text='Character n-gram order for Passim alignment (default: 7)', verbose_name='N-gram Order'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of this corpus and its sources', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='name',
            field=models.CharField(help_text="Name of the ground truth corpus (e.g., 'Sefaria Tanakh', 'Hebrew Literature Collection')", max_length=255, verbose_name='Corpus Name'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='owner',
            field=models.ForeignKey(help_text='User who created this corpus', on_delete=django.db.models.deletion.CASCADE, related_name='gt_corpora', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='source_path',
            field=models.CharField(blank=True, help_text='Path to source files or API endpoint', max_length=500, verbose_name='Source Path'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='source_type',
            field=models.CharField(choices=[('sefaria', 'Sefaria API'), ('pdf', 'PDF Files'), ('txt', 'Text Files'), ('manual', 'Manual Entry'), ('other', 'Other')], default='txt', help_text='Type of source for this corpus', max_length=50, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='total_characters',
            field=models.BigIntegerField(default=0, help_text='Total character count in corpus', verbose_name='Total Characters'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='total_texts',
            field=models.IntegerField(default=0, help_text='Number of texts in this corpus', verbose_name='Total Texts'),
        ),
        migrations.AlterField(
            model_name='groundtruthcorpus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Total number of characters in this text', verbose_name='Character Count'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='content',
            field=models.TextField(help_text='Clean text content ready for alignment with OCR', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='corpus',
            field=models.ForeignKey(help_text='The corpus this text belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='taba_pipeline.groundtruthcorpus', verbose_name='Corpus'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='filename',
            field=models.CharField(help_text='Original filename of the source document', max_length=255, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='language',
            field=models.CharField(default='heb', help_text="Language code (e.g., 'heb' for Hebrew, 'ara' for Arabic)", max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about this text (author, date, etc.)', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='title',
            field=models.CharField(help_text='Title or identifier for this text', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groundtruthtext',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Total number of words in this text', verbose_name='Word Count'),
        ),
    ]
