# Generated by Django 4.2.13 on 2025-10-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0022_invitation_expiry_date_user_expiry_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "verbose_name": "הודעת יצירת קשר",
                "verbose_name_plural": "הודעות יצירת קשר",
            },
        ),
        migrations.AlterModelOptions(
            name="groupowner",
            options={
                "verbose_name": "בעלים של קבוצה",
                "verbose_name_plural": "בעלי קבוצות",
            },
        ),
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "הזמנה",
                "verbose_name_plural": "הזמנות",
            },
        ),
        migrations.AlterModelOptions(
            name="quotaevent",
            options={
                "verbose_name": "אירוע מכסה",
                "verbose_name_plural": "אירועי מכסה",
            },
        ),
        migrations.AlterModelOptions(
            name="researchfield",
            options={"verbose_name": "תחום מחקר", "verbose_name_plural": "תחומי מחקר"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (("can_invite", "Can invite users"),),
                "verbose_name": "משתמש",
                "verbose_name_plural": "משתמשים",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "אנגלית"), ("he", "עברית"), ("fr", "צרפתית")],
                help_text="User's preferred language. If not set, system default language will be used.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="כתובת אימייל"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="צוות",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="workflow_state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "שגיאה"),
                    (1, "נוצר"),
                    (2, "נשלח"),
                    (4, "התקבל"),
                    (8, "אושר"),
                ],
                default=1,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="כתובת אימייל"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="legacy_mode",
            field=models.BooleanField(
                default=True,
                help_text="השתמש בגרסה הישנה של ממשק המשתמש. אם לא מסומן, תכונות שעדיין לא הועברו לממשק החדש עלולות להפוך לא זמינות. כמו כן, אם מסומן, תכונות חדשות יותר עלולות להפוך לא זמינות.",
            ),
        ),
    ]
