# -*- coding: utf-8 -*-
"""
🔄 Auto-generated Typology Translations (Hebrew)
================================================

⚠️  DO NOT EDIT MANUALLY!

This file was generated by: generate_typologies.py

To update, run:
    python generate_typologies.py

Data source: app/locale/he/LC_MESSAGES/django.po
"""

# Auto-generated from django.po
TYPOLOGY_TRANSLATIONS_HE = {
    "Alignment Job": "עבדות יישור",
    "Auth Token": "אסימון אימות",
    "CER Analysis": "ניתוח CER",
    "Document": "מסמך",
    "Line": "שורה",
    "OCR Model Language Analysis": "ניתוח שפה למודל OCR",
    "Page": "עמוד",
    "Title": "כותרת",
    "document": "מסמך",
    "line": "שורה",
}
