# Generated by Django 4.2.20 on 2025-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_documentpart_bw_backend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_batch_segmentation', models.IntegerField(default=1, help_text='Pages per segmentation task')),
                ('page_batch_recognition', models.IntegerField(default=1, help_text='Pages per transcription task')),
            ],
            options={
                'verbose_name': 'Instance setting',
                'verbose_name_plural': 'Instance settings',
            },
        ),
    ]
