# Generated by Django 4.2.23 on 2025-10-20 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0079_error_detection_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('method', models.CharField(choices=[('auto', 'Auto'), ('sequence', 'Sequence Matching'), ('levenshtein', 'Levenshtein Distance'), ('jaccard', 'Jaccard Similarity')], default='auto', max_length=50, verbose_name='Alignment Method')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Minimum similarity score (0-1) to consider a match', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Similarity Threshold')),
                ('min_length', models.IntegerField(default=10, help_text='Minimum characters to consider for alignment', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Text Length')),
                ('total_pairs', models.IntegerField(default=0, help_text='Number of aligned line pairs found', verbose_name='Total Pairs')),
                ('average_similarity', models.FloatField(default=0.0, help_text='Average similarity score across all pairs', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Average Similarity')),
                ('alignment_rate', models.FloatField(default=0.0, help_text='Percentage of lines successfully aligned', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Alignment Rate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alignments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document1', models.ForeignKey(help_text='First document in alignment', on_delete=django.db.models.deletion.CASCADE, related_name='alignments_as_doc1', to='core.document', verbose_name='Document 1')),
                ('document2', models.ForeignKey(help_text='Second document in alignment', on_delete=django.db.models.deletion.CASCADE, related_name='alignments_as_doc2', to='core.document', verbose_name='Document 2')),
            ],
            options={
                'verbose_name': 'Text Alignment',
                'verbose_name_plural': 'Text Alignments',
            },
        ),
        migrations.CreateModel(
            name='AlignmentPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(help_text='How similar the two lines are (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Similarity Score')),
                ('method_used', models.CharField(help_text='Algorithm used to calculate similarity', max_length=50, verbose_name='Method Used')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional alignment metadata (JSON)', verbose_name='Metadata')),
                ('is_verified', models.BooleanField(default=False, help_text='User has verified this alignment is correct', verbose_name='Verified')),
                ('is_rejected', models.BooleanField(default=False, help_text='User has rejected this alignment as incorrect', verbose_name='Rejected')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.textalignment', verbose_name='Alignment')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_pairs_as_line1', to='core.linetranscription', verbose_name='Line 1')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_pairs_as_line2', to='core.linetranscription', verbose_name='Line 2')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_alignments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Alignment Pair',
                'verbose_name_plural': 'Alignment Pairs',
            },
        ),
        migrations.CreateModel(
            name='AlignmentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('progress', models.IntegerField(default=0, help_text='Job completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress')),
                ('current_step', models.CharField(blank=True, help_text='Description of current processing step', max_length=200, verbose_name='Current Step')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Celery Task ID')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Detailed alignment results (JSON)', verbose_name='Result Data')),
                ('alignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='core.textalignment', verbose_name='Alignment')),
            ],
            options={
                'verbose_name': 'Alignment Job',
                'verbose_name_plural': 'Alignment Jobs',
            },
        ),
        migrations.AddIndex(
            model_name='textalignment',
            index=models.Index(fields=['document1', 'document2'], name='core_textal_documen_9e1492_idx'),
        ),
        migrations.AddIndex(
            model_name='textalignment',
            index=models.Index(fields=['status'], name='core_textal_status_ff20db_idx'),
        ),
        migrations.AddIndex(
            model_name='textalignment',
            index=models.Index(fields=['created_at'], name='core_textal_created_a304fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textalignment',
            unique_together={('document1', 'document2')},
        ),
        migrations.AddIndex(
            model_name='alignmentpair',
            index=models.Index(fields=['alignment', 'similarity'], name='core_alignm_alignme_119b06_idx'),
        ),
        migrations.AddIndex(
            model_name='alignmentpair',
            index=models.Index(fields=['is_verified'], name='core_alignm_is_veri_42c01c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alignmentpair',
            unique_together={('alignment', 'line1', 'line2')},
        ),
        migrations.AddIndex(
            model_name='alignmentjob',
            index=models.Index(fields=['task_id'], name='core_alignm_task_id_7e609f_idx'),
        ),
        migrations.AddIndex(
            model_name='alignmentjob',
            index=models.Index(fields=['started_at'], name='core_alignm_started_c64d8a_idx'),
        ),
    ]
