# Generated by Django 4.2.20 on 2025-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_legacy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
